server:
  port: 8088

spring:
  datasource:
    platform: h2
  h2:
    console:
      path: /auth/console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  jackson:
      serialization:
        INDENT_OUTPUT: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
# Specify the DirectoryProvider to use (the Lucene Directory)
#spring.jpa.properties.hibernate.search.default.directory_provider = filesystem

# Using the filesystem DirectoryProvider you also have to specify the default
# base directory for all indexes (make sure that the application have write
# permissions on such directory)
#spring.jpa.properties.hibernate.search.default.indexBase = /home/mrmodise/lucene/indexes/
